# Project names should contain only (lowercase, number, underscore) characters
name: 'dbt_yellow19_bq'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_yellow19_bq'

# These configurations specify where dbt should look for different types of files. leave it as default!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Define materialized as one of: table, view, incremental, & ephemeral
models:
  dbt_yellow19_bq:
    nytaxi:
      +docs:
        node_color: "blue"
    warehouse:
      +materialized: table
      +docs:
        node_color: "green"
    staging:
      +materialized: view
    other:
      +materialized: view
      +docs:
        node_color: "purple"
